language: node_js
node_js: stable

install:
  - npm install

  script:
  - npm run build

after_script:
  - cd ./static
  - git init
  - git config user.name "QinZonger"
  - git config user.email "17611573068@163.com"
  - git add .
  - git commit -m "Update"
  - git push --force --quiet "https://${GitHub_token}@${GH_REF}" master:master

branches:
  only:
  - master
env:
 global:
  - GH_REF: git@github.com:QinZonger/react-app.git
